# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rmvnorm <- function(mean, Precision) {
    .Call('_ModSoftBart_rmvnorm', PACKAGE = 'ModSoftBart', mean, Precision)
}

choll <- function(Sigma) {
    .Call('_ModSoftBart_choll', PACKAGE = 'ModSoftBart', Sigma)
}

update_sigma <- function(r, sigma_hat, sigma_old, temperature) {
    .Call('_ModSoftBart_update_sigma', PACKAGE = 'ModSoftBart', r, sigma_hat, sigma_old, temperature)
}

rlgam <- function(shape) {
    .Call('_ModSoftBart_rlgam', PACKAGE = 'ModSoftBart', shape)
}

SoftBart <- function(X, Y, X_test, group, alpha, alpha_comp, beta, gamma, sigma, shape, width, num_tree, sigma_hat, k, alpha_scale, alpha_comp_scale, alpha_shape_1, alpha_shape_2, alpha_comp_shape_1, alpha_comp_shape_2, tau_rate, num_tree_prob, temperature, weights, num_burn, num_thin, num_save, num_print, update_sigma_mu, update_s, update_alpha, update_beta, update_gamma, update_tau, update_tau_mean, update_num_tree, update_sigma) {
    .Call('_ModSoftBart_SoftBart', PACKAGE = 'ModSoftBart', X, Y, X_test, group, alpha, alpha_comp, beta, gamma, sigma, shape, width, num_tree, sigma_hat, k, alpha_scale, alpha_comp_scale, alpha_shape_1, alpha_shape_2, alpha_comp_shape_1, alpha_comp_shape_2, tau_rate, num_tree_prob, temperature, weights, num_burn, num_thin, num_save, num_print, update_sigma_mu, update_s, update_alpha, update_beta, update_gamma, update_tau, update_tau_mean, update_num_tree, update_sigma)
}

do_mh <- function(loglik_new, loglik_old, new_to_old, old_to_new) {
    .Call('_ModSoftBart_do_mh', PACKAGE = 'ModSoftBart', loglik_new, loglik_old, new_to_old, old_to_new)
}

